{% set name = "elasticsearch-dsl" %}
{% set version = "5.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "cbef6467085d7debc870bc450d996c7ba5b8822eb86a6033bba09134ffb01ba8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six
    - python-dateutil
    - elasticsearch >=5.4.0,<6.0.0
    - ipaddress  # [py<33]

test:
  imports:
    - elasticsearch_dsl

about:
  home: https://github.com/elasticsearch/elasticsearch-dsl-py
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Higher-level Python client for Elasticsearch
  dev_url: https://github.com/elasticsearch/elasticsearch-dsl-py
  doc_url: https://elasticsearch-dsl.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
